name: Package flags and upload to S3

on:
  push:
    branches: [ main ]

concurrency:
  group: dorkly
  cancel-in-progress: false

env:
  DORKLY_S3_BUCKET: ${{ vars.AWS_S3_BUCKET }}
#  AWS_DEFAULT_REGION: ${{ vars.AWS_REGION }}
#  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ vars.AWS_REGION }}

    - name: Set up Go
      uses: actions/setup-go@v5 # see https://github.com/actions/setup-go/tags for latest version
      with:
        go-version: '1.22.2'

    - name: Process flag changes and upsert to S3
      run: go run github.com/dorklyorg/dorkly/cmd/dorkly@${{ vars.DORKLY_VERSION }}