name: Pull Request

on:
  pull_request:
    branches: [main]
    types: [opened, reopened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5 # see https://github.com/actions/setup-go/tags for latest version
      with:
        go-version: '1.22.2'

    - name: Build go binary
      run: go install github.com/dorklyorg/dorkly/cmd/validator@${{ inputs.dorkly-version || vars.DORKLY_VERSION }}

    - name: run validator
      run: validator